apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: spring-petclinic-role-binding
  namespace: spring-petclinic-user1
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
- kind: ServiceAccount
  name: argocd-argocd-application-controller
  namespace: argocd-user1
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: spring-petclinic-ns-allowing-myns-argo-role
  namespace: spring-petclinic-user1
rules:
- apiGroups:
  - "*"
  resources:
  - "*"
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: spring-petclinic-ns-allowing-myns-argo-rolebinding
  namespace: spring-petclinic-user1
subjects:
- kind: ServiceAccount
  name: argocd-argocd-application-controller
  namespace: argocd-user1
roleRef:
  kind: Role
  name: spring-petclinic-ns-allowing-myns-argo-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: spring-petclinic-prod-role-binding
  namespace: spring-petclinic-prod-user1
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
- kind: ServiceAccount
  name: argocd-argocd-application-controller
  namespace: argocd-user1
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: spring-petclinic-ns-allowing-myns-argo-role
  namespace: spring-petclinic-prod-user1
rules:
- apiGroups:
  - "*"
  resources:
  - "*"
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: spring-petclinic-ns-allowing-myns-argo-rolebinding
  namespace: spring-petclinic-prod-user1
subjects:
- kind: ServiceAccount
  name: argocd-argocd-application-controller
  namespace: argocd-user1
roleRef:
  kind: Role
  name: spring-petclinic-ns-allowing-myns-argo-role
  apiGroup: rbac.authorization.k8s.io
