apiVersion: v1
kind: Namespace
metadata:
  name: argocd-user2
spec:
  finalizers:
  - kubernetes
---
apiVersion: v1
kind: Namespace
metadata:
  name: spring-petclinic-user2
spec:
  finalizers:
  - kubernetes
---
apiVersion: v1
kind: Namespace
metadata:
  name: spring-petclinic-prod-user2
spec:
  finalizers:
  - kubernetes
