apiVersion: v1
kind: Namespace
metadata:
  name: argocd-user6
spec:
  finalizers:
  - kubernetes
---
apiVersion: v1
kind: Namespace
metadata:
  name: spring-petclinic-user6
spec:
  finalizers:
  - kubernetes
---
apiVersion: v1
kind: Namespace
metadata:
  name: spring-petclinic-prod-user6
spec:
  finalizers:
  - kubernetes
