apiVersion: v1
kind: Namespace
metadata:
  name: argocd-user20
spec:
  finalizers:
  - kubernetes
---
apiVersion: v1
kind: Namespace
metadata:
  name: spring-petclinic-user20
spec:
  finalizers:
  - kubernetes
---
apiVersion: v1
kind: Namespace
metadata:
  name: spring-petclinic-prod-user20
spec:
  finalizers:
  - kubernetes
