apiVersion: v1
kind: Namespace
metadata:
  name: argocd-user3
spec:
  finalizers:
  - kubernetes
---
apiVersion: v1
kind: Namespace
metadata:
  name: spring-petclinic-user3
spec:
  finalizers:
  - kubernetes
---
apiVersion: v1
kind: Namespace
metadata:
  name: spring-petclinic-prod-user3
spec:
  finalizers:
  - kubernetes
