apiVersion: v1
kind: Namespace
metadata:
  name: argocd-user05
spec:
  finalizers:
  - kubernetes
---
apiVersion: v1
kind: Namespace
metadata:
  name: spring-petclinic-user05
spec:
  finalizers:
  - kubernetes
---
apiVersion: v1
kind: Namespace
metadata:
  name: spring-petclinic-prod-user05
spec:
  finalizers:
  - kubernetes
